name: train
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.11.11
  - numpy
  - wandb=0.20.1
  - omegaconf=2.3.0
  - datasets=3.5.0
  - hydra-core=1.3.2
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=12.4
  - accelerate=1.7.0
  - langdetect=1.0.9
  - transformers=4.52.4
  - sentencepiece=0.2.0
  # - pandas
  # - matplotlib
  - pip=24.1.2
  - pip:
      # - torch==2.6.0
      # - torchvision==0.21.0
      - tensor-parallel==1.3.0
      # - protobuf>=4.23.3
  # - pip_args: --index-url https://download.pytorch.org/whl/cu124
